# Generated by Django 4.1.3 on 2023-01-20 11:27

from django.db import migrations
from order.seed import forwards_func, reverse_func

class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
